name: Reset Heroku
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
  
      - name: Restart Heroku dynos
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:restart --app sparkproxy
