name: Restart Heroku Dynos

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  restart-dynos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Restart Heroku dynos
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:restart --app sparkproxy
